"""Persist and load Z account credentials in ~/.z/credentials."""

from __future__ import annotations

import json
import os
import time
from dataclasses import asdict, dataclass, field
from pathlib import Path
from typing import Any

from .paths import CREDENTIALS_ENV_PATH, CREDENTIALS_PATH, ensure_z_home


@dataclass
class WorkspaceContext:
    id: str | None = None
    name: str | None = None
    role: str | None = None
    organization: str | None = None


@dataclass
class UserProfile:
    id: str | None = None
    email: str | None = None
    name: str | None = None
    phone: str | None = None
    provider: str | None = None  # google | email | phone


@dataclass
class Credentials:
    access_token: str
    refresh_token: str | None = None
    token_type: str = "Bearer"
    expires_at: float | None = None  # unix timestamp
    user: UserProfile = field(default_factory=UserProfile)
    workspace: WorkspaceContext = field(default_factory=WorkspaceContext)

    def is_expired(self, skew_seconds: int = 60) -> bool:
        if not self.expires_at:
            return False
        return time.time() >= (self.expires_at - skew_seconds)

    def is_authenticated(self) -> bool:
        return bool(self.access_token) and not self.is_expired()

    def display_name(self) -> str:
        if self.user and self.user.name:
            return self.user.name
        if self.user and self.user.email:
            return self.user.email
        if self.user and self.user.phone:
            return self.user.phone
        return "Z user"

    def to_dict(self) -> dict[str, Any]:
        return {
            "access_token": self.access_token,
            "refresh_token": self.refresh_token,
            "token_type": self.token_type,
            "expires_at": self.expires_at,
            "user": asdict(self.user) if self.user else {},
            "workspace": asdict(self.workspace) if self.workspace else {},
        }

    @classmethod
    def from_dict(cls, data: dict[str, Any]) -> Credentials:
        user_data = data.get("user") or {}
        ws_data = data.get("workspace") or {}
        return cls(
            access_token=data.get("access_token") or "",
            refresh_token=data.get("refresh_token"),
            token_type=data.get("token_type") or "Bearer",
            expires_at=data.get("expires_at"),
            user=UserProfile(
                **{k: user_data.get(k) for k in ("id", "email", "name", "phone", "provider")}
            ),
            workspace=WorkspaceContext(
                **{k: ws_data.get(k) for k in ("id", "name", "role", "organization")}
            ),
        )


def load_credentials(path: Path | None = None) -> Credentials | None:
    path = path or CREDENTIALS_PATH
    if not path.exists():
        return None
    try:
        data = json.loads(path.read_text(encoding="utf-8"))
        creds = Credentials.from_dict(data)
        if not creds.access_token:
            return None
        return creds
    except (OSError, json.JSONDecodeError, TypeError, ValueError):
        return None


def save_credentials(creds: Credentials, path: Path | None = None) -> Path:
    ensure_z_home()
    path = path or CREDENTIALS_PATH
    path.write_text(json.dumps(creds.to_dict(), indent=2) + "\n", encoding="utf-8")
    try:
        path.chmod(0o600)
    except OSError:
        pass
    _write_credentials_env(creds)
    # Expose for the current process so workspace features can read it
    os.environ["Z_ACCESS_TOKEN"] = creds.access_token
    if creds.user and creds.user.email:
        os.environ["Z_USER_EMAIL"] = creds.user.email
    if creds.workspace and creds.workspace.id:
        os.environ["Z_WORKSPACE_ID"] = creds.workspace.id
    return path


def _write_credentials_env(creds: Credentials) -> None:
    """Mirror token into a dotenv file (loaded early by main, like oauth-keys.env)."""
    lines = [
        "# Generated by `z login` — do not commit",
        f"Z_ACCESS_TOKEN={creds.access_token}",
    ]
    if creds.refresh_token:
        lines.append(f"Z_REFRESH_TOKEN={creds.refresh_token}")
    if creds.user and creds.user.email:
        lines.append(f"Z_USER_EMAIL={creds.user.email}")
    if creds.user and creds.user.id:
        lines.append(f"Z_USER_ID={creds.user.id}")
    if creds.workspace and creds.workspace.id:
        lines.append(f"Z_WORKSPACE_ID={creds.workspace.id}")
    CREDENTIALS_ENV_PATH.write_text("\n".join(lines) + "\n", encoding="utf-8")
    try:
        CREDENTIALS_ENV_PATH.chmod(0o600)
    except OSError:
        pass


def clear_credentials(path: Path | None = None) -> None:
    path = path or CREDENTIALS_PATH
    for p in (path, CREDENTIALS_ENV_PATH):
        try:
            if p.exists():
                p.unlink()
        except OSError:
            pass
    for key in ("Z_ACCESS_TOKEN", "Z_REFRESH_TOKEN", "Z_USER_EMAIL", "Z_USER_ID", "Z_WORKSPACE_ID"):
        os.environ.pop(key, None)


def apply_credentials_to_env(creds: Credentials | None = None) -> Credentials | None:
    """Load credentials (if needed) and export into the process environment."""
    creds = creds or load_credentials()
    if not creds or not creds.is_authenticated():
        return None
    os.environ["Z_ACCESS_TOKEN"] = creds.access_token
    if creds.user and creds.user.email:
        os.environ["Z_USER_EMAIL"] = creds.user.email
    if creds.user and creds.user.id:
        os.environ["Z_USER_ID"] = creds.user.id
    if creds.workspace and creds.workspace.id:
        os.environ["Z_WORKSPACE_ID"] = creds.workspace.id
    return creds
